name: Build and Deploy

on:
  push:
    branches: ['master']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm i
      - name: Build SASS
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v2
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          # Upload entire repository
          path: '.'
      - name: Test Build Unit Tests
        run: npm run test-unit

      - name: Test Build End-To-End Tests
        run: npm run test-e2e-cli
        env:
          CYPRESS_LOGIN_USERNAME: ${{ secrets.LOGIN_USERNAME }}
          CYPRESS_LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}


      - name: Deploy to GitHub Pages
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git checkout gh-pages  # Or the branch where your GitHub Pages site is hosted
          git merge main --no-commit --no-ff
          git commit -m "Auto-deployed changes"
          git push
